version: "3.1"
services:
  hastebin:
    image: rlister/hastebin
    ports:
      - "7777:7777"
    networks:
      - hastyPop
    environment:
      STORAGE_TYPE: redis 
      STORAGE_HOST: redhaste
      STORAGE_DB: 0
    links:
      - redhaste 

  redhaste:
    image: redis:4.0.1
    container_name: redhaste
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data 
    ports:
      - "7979:6379"
    networks:
      - hastyPop

  redis-monitor:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=dev:redhaste:6379
    ports:
      - 7981:8081
    networks:
      - hastyPop

networks:
  hastyPop:

